---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-pv-claim  # should match with the deployment object >> volumes >> claimName
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
