apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
spec:
  type: LoadBalancer
  selector:
    app: packersmovers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
#http://a0f6a6a2a0cce4c6492ea2ea16c07f70-1019895947.us-east-2.elb.amazonaws.com/customer/ping
