# ##############################################cluster##################################
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
spec:
  type: ClusterIP
  selector:
    app: packersmovers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    # targetPort: 5000

    login into the one of the worker node and take secondary Ip and curl <ip-address>
```
#######################################################Load Balancer#######################################
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
spec:
  type: LoadBalancer
  selector:
    app: packersmovers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    # targetPort: 5000
```


CLassic loadbalancer DNS  if you want see the target group also SG 80 should be enable automatically

Change the service name for LB one more Lb will created 
################################################################Node Port##############################
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
spec:
  type:  NodePort
  selector:
    app: packersmovers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
...


To access the application:

http://ip:nodeport
http://3.144.188.160:30007
