apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-02eb08ed063799a83
    fsType: ext4
  storageClassName: standard
