---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
    version: v1
spec:
  type: LoadBalancer # classic load balancer will created
  selector:
    app: packersmovers
    version: v1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
...
