apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weshopify-db-pvc
spec:
  volumeName: weshopify-db-pv      
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-storage
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
