apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: centos-container
    image: centos:7
    command: ["/bin/bash", "-c", "echo 'Hello Vijay!' > /data/hello.txt && sleep 3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /data
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp/vijaydata
      type: DirectoryOrCreate


kubectl apply -f hostpath-demo.yaml
kubectl get pods
kubectl exec -it hostpath-demo -- /bin/bash
cat /data/hello.txt
cat /tmp/vijaydata/hello.txt


