---
apiVersion: v1
kind: ReplicationController
metadata:
  name: customer
  labels:
    app: packersmovers
spec:
  replicas: 5
  minReadySeconds: 10
  selector:
      namee: packes
      app: packersmovers
  template:
    metadata:
      labels:
        app: packersmovers
    spec:
      containers:
      - name: customer
        image: 573567580560.dkr.ecr.ap-south-1.amazonaws.com/customer:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: packersmovers
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
...
