---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: packersmovers
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: packersmovers
  template:
    metadata:
      labels:
        app: packersmovers
    spec:
      containers:
      - name: customer
        image: 841162679093.dkr.ecr.us-east-1.amazonaws.com/customer:5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
spec:
  type:  NodePort
  selector:
    app: packersmovers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
...


notes: 
1. kubectl delete all --all
2. kubectl apply -f recreate.yaml
3. kubectl get all # see the pod service deployment replicaSet
4. kubectl get deployment or deploy
5. kubectl get pods -o wide
6. kubectl get svc
7. kubectl scale deployment frontend/customer replicas 5/3/2/1
8. kubectl delete pod <POD-NAME> ##  pod will create
9. kubectl delete deployment <DEPLOYMENT_NAME> # now deployment delete

access:
add the sg 30007
http://<IP-addree-worker-nodes>:30007
